using System.Text.Json;
using System.Text.Json.Nodes;
using Archon.Core.Output;
using Archon.Core.Rules;

namespace Archon.Core.Configuration;

/// <summary>
/// Produces a JSON Schema for <c>.archon.json</c>.
///
/// <see cref="ConfigValidator"/> reports a mistyped entry after a run; this prevents most of them
/// being typed. Every editor that reads <c>$schema</c> then offers the rule ids as completions,
/// shows each rule's title on hover, and marks an unknown key or a severity outside the permitted
/// set as you write it — which is a shorter feedback loop than any message the tool can print.
///
/// The schema is generated from the registry rather than written by hand, so it lists the rules
/// this installation actually has, including those from external packs. A hand-maintained file
/// would list the built-in rules and go stale on the first one added, and could never describe a
/// private pack at all. Regenerate it with <c>archon schema</c> after adding or upgrading a pack.
/// </summary>
public static class ConfigSchema
{
    /// <summary>The conventional name, sitting beside the configuration file it describes.</summary>
    public const string FileName = ".archon.schema.json";

    private static readonly JsonSerializerOptions WriteOptions = new() { WriteIndented = true };

    /// <summary>The top-level keys a configuration file may contain, as the loader binds them.</summary>
    public static readonly string[] KnownKeys =
    {
        "rules", "exclude", "layers", "rulePacks", "options", "baseline"
    };

    public static string Generate(RuleRegistry registry)
    {
        var schema = new JsonObject
        {
            ["$schema"] = "http://json-schema.org/draft-07/schema#",
            ["title"] = "Archon configuration",
            ["description"] =
                "Configuration for Archon, found by walking up from the analysed path. "
                + "Generated by 'archon schema' from the rules currently registered.",
            ["type"] = "object",

            // Closed deliberately. A misspelled top-level key — "rule" for "rules" — binds to
            // nothing and leaves a file that reads as configured while doing nothing, which is the
            // whole class of mistake this schema exists to catch.
            ["additionalProperties"] = false,
            ["properties"] = new JsonObject
            {
                ["$schema"] = new JsonObject
                {
                    ["type"] = "string",
                    ["description"] = "Path to this schema. Ignored by Archon; read by editors."
                },
                ["rules"] = RulesProperty(registry),
                ["exclude"] = new JsonObject
                {
                    ["type"] = "array",
                    ["items"] = new JsonObject { ["type"] = "string" },
                    ["description"] =
                        "Path globs never analysed, relative to the workspace root. Added to the "
                        + "defaults (bin, obj, node_modules, .git) rather than replacing them.",
                    ["examples"] = new JsonArray { "**/Generated/**", "**/*.Designer.cs" }
                },
                ["layers"] = LayersProperty(),
                ["rulePacks"] = new JsonObject
                {
                    ["type"] = "array",
                    ["items"] = new JsonObject { ["type"] = "string" },
                    ["description"] =
                        "Assembly paths providing additional IRulePack implementations, absolute or "
                        + "relative to the workspace root. A pack that fails to load is reported and skipped."
                },
                ["options"] = OptionsProperty(registry),
                ["baseline"] = new JsonObject
                {
                    ["type"] = "string",
                    ["default"] = ".archon-baseline.json",
                    ["description"] =
                        "Where accepted findings are recorded. Those findings are still reported, "
                        + "but only new ones fail a check."
                }
            }
        };

        return schema.ToJsonString(WriteOptions);
    }

    /// <summary>
    /// A severity-valued property, with the permitted words written out in place.
    ///
    /// Inlined rather than referred to a shared definition on purpose. Draft-07 says a schema
    /// containing <c>$ref</c> ignores its siblings, so a <c>description</c> written next to a
    /// <c>$ref</c> is not required to be shown — and the per-rule descriptions are the entire point
    /// of generating this file. Repeating the five words costs a few kilobytes in a generated
    /// artefact and buys the same behaviour in every editor rather than only the lenient ones.
    /// </summary>
    private static JsonObject SeverityValue(string description) => new()
    {
        ["enum"] = ToArray(ArchonConfig.SeverityNames),
        ["description"] = description
    };

    /// <summary>
    /// The <c>rules</c> map, with one named property per rule id and per category so that both are
    /// offered as completions. <c>additionalProperties</c> stays open at the severity type: a rule
    /// id from a pack that is configured but not currently loadable must not be marked as an error.
    /// </summary>
    private static JsonObject RulesProperty(RuleRegistry registry)
    {
        var properties = new JsonObject();

        foreach (RegisteredRule registered in registry.Descriptors.OrderBy(r => r.Descriptor.Id, StringComparer.Ordinal))
        {
            RuleDescriptor descriptor = registered.Descriptor;
            properties[descriptor.Id] = SeverityValue(
                $"{descriptor.Title} ({descriptor.Category}, {registered.Rule.Scope.ToString().ToLowerInvariant()} scope, "
                + $"default {Reporter.Label(descriptor.DefaultSeverity)}). {descriptor.Description}");
        }

        var byCategory = registry.Descriptors
            .GroupBy(r => r.Descriptor.Category, StringComparer.OrdinalIgnoreCase)
            .OrderBy(g => g.Key, StringComparer.Ordinal);

        foreach (IGrouping<string, RegisteredRule> category in byCategory)
        {
            // A category name and a rule id share one keyspace, so a pack declaring a category that
            // collides with an id would overwrite it here. The id wins, matching SeverityFor.
            if (properties.ContainsKey(category.Key))
            {
                continue;
            }
            string ids = string.Join(", ", category.Select(r => r.Descriptor.Id).OrderBy(i => i, StringComparer.Ordinal));
            properties[category.Key] = SeverityValue(
                $"Category: sets {ids} at once. An entry for a specific rule id always wins over its category.");
        }

        return new JsonObject
        {
            ["type"] = "object",
            ["description"] =
                "Severity per rule id, or per category to set a whole family at once. "
                + "An explicit rule id always wins over its category.",
            ["properties"] = properties,

            // Left open at the severity type rather than closed to the ids above: a configuration
            // may name a rule from a pack that is not loadable on this machine, and an editor must
            // not mark that as an error merely because the assembly is absent here.
            ["additionalProperties"] = SeverityValue(
                "Severity for a rule id this installation does not have registered, such as one from "
                + "a rule pack that is not currently loadable.")
        };
    }

    private static JsonObject LayersProperty()
    {
        var edge = new JsonObject
        {
            ["type"] = "object",
            ["required"] = new JsonArray { "from", "to" },
            ["additionalProperties"] = false,
            ["properties"] = new JsonObject
            {
                ["id"] = new JsonObject
                {
                    ["type"] = "string",
                    ["description"] = "A name for this edge, quoted back in the finding message."
                },
                ["from"] = new JsonObject
                {
                    ["type"] = "string",
                    ["description"] = "The referencing layer. Must match a key of \"layers\" exactly; case is significant."
                },
                ["to"] = new JsonObject
                {
                    ["type"] = "string",
                    ["description"] = "The referenced layer. Must match a key of \"layers\" exactly; case is significant."
                }
            }
        };

        return new JsonObject
        {
            ["type"] = "object",
            ["additionalProperties"] = false,
            ["description"] =
                "Layer definitions and permitted dependency direction. AR0001 stays silent until "
                + "\"layers\" declares at least one layer.",
            ["properties"] = new JsonObject
            {
                ["mode"] = new JsonObject
                {
                    ["enum"] = new JsonArray { "denylist", "allowlist" },
                    ["default"] = "denylist",
                    ["description"] =
                        "denylist forbids only the edges in \"deny\"; allowlist permits only those in "
                        + "\"allow\". Anything else is treated as denylist, which is the permissive reading."
                },
                ["layers"] = new JsonObject
                {
                    ["type"] = "object",
                    ["additionalProperties"] = new JsonObject
                    {
                        ["type"] = "array",
                        ["items"] = new JsonObject { ["type"] = "string" }
                    },
                    ["description"] =
                        "Layer name to the namespace prefixes belonging to it. A file whose namespace "
                        + "matches no prefix is never flagged."
                },
                ["deny"] = new JsonObject
                {
                    ["type"] = "array",
                    ["items"] = edge.DeepClone(),
                    ["description"] = "Forbidden edges. Read only when mode is denylist."
                },
                ["allow"] = new JsonObject
                {
                    ["type"] = "array",
                    ["items"] = edge.DeepClone(),
                    ["description"] = "Permitted edges. Read only when mode is allowlist."
                }
            }
        };
    }

    /// <summary>
    /// The <c>options</c> map. Each rule defines its own option shape and the engine never inspects
    /// one, so the value stays an open object; only the keys are constrained, to rule ids that exist.
    /// </summary>
    private static JsonObject OptionsProperty(RuleRegistry registry)
    {
        var properties = new JsonObject();
        foreach (RegisteredRule registered in registry.Descriptors.OrderBy(r => r.Descriptor.Id, StringComparer.Ordinal))
        {
            properties[registered.Descriptor.Id] = new JsonObject
            {
                ["type"] = "object",
                ["description"] = $"Options read by {registered.Descriptor.Id} ({registered.Descriptor.Title})."
            };
        }

        return new JsonObject
        {
            ["type"] = "object",
            ["description"] = "Per-rule option objects, keyed by rule id. A rule that reads none ignores its entry.",
            ["properties"] = properties,
            ["additionalProperties"] = new JsonObject { ["type"] = "object" }
        };
    }

    private static JsonArray ToArray(IEnumerable<string> values)
    {
        var array = new JsonArray();
        foreach (string value in values)
        {
            array.Add(value);
        }
        return array;
    }
}
